M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Wed 19 Jan 2022 12:48:58 AM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-19T00:48:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.030
%
G90
G05
T2
X55.85Y-81.5
T3
X60.0Y-53.0
X90.0Y-97.0
T4
X59.12Y-63.185
X59.12Y-74.615
T1
X55.85Y-88.79G85X55.85Y-89.21
G05
T0
M30
